### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by mrtj**
I translated the labels in Italian. You might want to refactor the language selector widget. Unfortunately I don't have the necessary skills to do it.

### CODE REVIEW

**Comment by vdavid** [comment]
Wow, cool stuff, János. :) The only imperfect thing about it is that the top-right language switcher is currently implemented to be bilingual, would need a more sophisticated solution to make it work for 3+ languages. If you have time to implement that, I'm happy to review it, otherwise, it at least works via the https://covidevent.info/it/ direct link.

**Comment by vdavid** [comment]
Also, there are 2 new strings that I've just added as per the request of many. If you could translate these two to Italian, and send them in a PR or via a simple message here, that'd be awesome. I hope there won't be much more, I don't intend to develop this tool much further.
The two new phrases are:

- There is no consensus on what “crowded” means. As a rule of thumb, use 1–1.5m distance from others.
- There is no consensus on what “short time” means. As a rule of thumb, use 15 minutes.

**Comment by mrtj** [comment]
The two phrases in Italian would be:
 - Non abbiamo una definizione formale di "affollato". Come regola generale considera 1-1.5m tra le persone.
 - Non abbiamo una definizione formale di "breve periodo di tempo". Come regola generale considera 15 minuti.

Unfortunately I don't have the necessary js/react skills to implement a more sophisticated language switcher.

**Comment by vdavid** [comment]
Thanks, I've added the 2 phrases. I'll add the Italian link if I get the
time :)

**Pull request merged**
